server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: http://auth-service:8086
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - PreserveHostHeader
        - id: product-service
          uri: http://product-service:8088
          predicates:
            - Path=/api/products/**,/api/categories/**,/uploads/**,/api/wishlist/**,/api/wishlist
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/api/orders/**,/api/orders,/api/cart/**,/api/cart
          filters:
            - AddRequestHeader=X-API-KEY, secret-api-key
        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/api/inventory/**, /api/inventory
        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/api/payments/**, /api/payments
        - id: analytics-service
          uri: http://analytics-service:8085
          predicates:
            - Path=/api/analytics/**, /api/analytics
        - id: auth-service-health
          uri: http://auth-service:8086
          predicates:
            - Path=/health/auth
          filters:
            - SetPath=/actuator/health
        - id: order-service-health
          uri: http://order-service:8081
          predicates:
            - Path=/health/orders
          filters:
            - SetPath=/actuator/health
        - id: analytics-service-health
          uri: http://analytics-service:8085
          predicates:
            - Path=/health/analytics
          filters:
            - SetPath=/actuator/health
        - id: inventory-service-health
          uri: http://inventory-service:8082
          predicates:
            - Path=/health/inventory
          filters:
            - SetPath=/actuator/health
        - id: payment-service-health
          uri: http://payment-service:8083
          predicates:
            - Path=/health/payments
          filters:
            - SetPath=/actuator/health
        - id: product-service-health
          uri: http://product-service:8088
          predicates:
            - Path=/health/products
          filters:
            - SetPath=/actuator/health

jwt:
  secret: M/wZlUpJUUTKSwRfDkPgLHCwalDUxt/hEx/tgtaxWoA=

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
